last

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,14 +1,28 @@
 #!/usr/bin/env bash
-
-#+    leads to the file to be transferred.
-#+    IP of the server to transfer the file to.
-#+    This username scp connects.
-#+    Path to SSH private scp key.
-# By: Don
+# checking the commandline arguments
 
 if [ $# -lt 4 ]
 then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
+fi
+
+# assigns parameters to the vars
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_keys=$4
+
+# disabling the checing of strict host key
+
+scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+
+# to check if transfer is succesful
+if [ $? -eq 0 ]
+then
+	echo "THE FILE TRANSFER SUCCESFUL"
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+	echo "THE FILE TRANSFER FAIL"
 fi
